Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using IvanCafe.Models;
using IvanCafe.ViewModels;

namespace IvanCafe.Controllers
{
    public class CartController : Controller
    {
        PubDbContext db = new PubDbContext();
        
        // GET: /Cart/
        public ActionResult Index()
        {
            var cart = Cart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new OrderViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the product from the database
            var addedProduct = db.Products
                .Single(product => product.Id == id);

            // Add it to the shopping cart
            var cart = Cart.GetCart(this.HttpContext);

            cart.AddToCart(addedProduct);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /Cart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = Cart.GetCart(this.HttpContext);

            // Get the name of the product to display confirmation
            string productName = db.CartItems
                .Single(item => item.CartItemId == id).Product.Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new RemoveFromOrderViewModel
            {
                Message = Server.HtmlEncode(productName) +
                    " has been removed from your order.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /Cart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = Cart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("_CartCount");
        }
    }
}

Controllers/OrderDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IvanCafe.Models;

namespace IvanCafe.Controllers
{
    public class OrderDetailController : Controller
    {
        private PubDbContext db = new PubDbContext();

        // GET: OrderDetail
        public ViewResult Index(string sortOrder, string searchString)
        {
            ViewBag.UsernameSortParm = String.IsNullOrEmpty(sortOrder) ? "by_user" : "";
            ViewBag.ProductSortParm = sortOrder == "Product" ? "by_product" : "Product";
            var orderDetails = from o in db.OrderDetails select o;
            var orders = from d in db.Orders select d;

            if (!String.IsNullOrEmpty(searchString))
            {
                orderDetails = orderDetails.Where(o => o.Order.Username.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "by_user":
                    orderDetails = orderDetails.OrderByDescending(o => o.Id);
                    break;
                case "Product":
                    orderDetails = orderDetails.OrderBy(o => o.ProductId);
                    break;
                case "by_product":
                    orderDetails = orderDetails.OrderByDescending(o => o.ProductId);
                    break;
                default:
                    orderDetails = orderDetails.OrderBy(o => o.Id);
                    break;
            }
            return View(orderDetails.ToList());
        }

       
        // GET: OrderDetail/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderDetail orderDetail = db.OrderDetails.Find(id);
            if (orderDetail == null)
            {
                return HttpNotFound();
            }
            return View(orderDetail);
        }
    }
}

Controllers/ProductController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IvanCafe.Models;

namespace IvanCafe.Controllers
{
    public class ProductController : Controller
    {
        private PubDbContext db = new PubDbContext();

        // GET: Product
        public ActionResult Index(int? productTypeID)
        {

                var all = db.Products
                    .Include(p => p.ProductType)
                    .Where(p => p.ProductTypeId == productTypeID || productTypeID == null);
                return View(all.ToList());

        }

        // GET: Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            ViewBag.ProductTypeId = new SelectList(db.ProductTypes, "Id", "Name");
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ProductTypeId,Description,Price,IsForSale")] Product product, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string ImageName = System.IO.Path.GetFileName(file.FileName);
                    string physicalPath = Server.MapPath("~/App_Data/Images/" + ImageName);
                    file.SaveAs(physicalPath);

                    product.ImageName = ImageName;
                }

                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductTypeId = new SelectList(db.ProductTypes, "Id", "Name", product.ProductTypeId);
            return View(product);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductTypeId = new SelectList(db.ProductTypes, "Id", "Name", product.ProductTypeId);
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ProductTypeId,Description,Price,IsForSale")] Product product, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)


                {
                    string ImageName = System.IO.Path.GetFileName(file.FileName);
                    string physicalPath = Server.MapPath("~/Content/Images/" + ImageName);
                    file.SaveAs(physicalPath);

                    product.ImageName = ImageName;
                }


                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductTypeId = new SelectList(db.ProductTypes, "Id", "Name", product.ProductTypeId);
            return View(product);
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Carousel.cshtml
<div class="container">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="~/Content/Images/ousidebw.jpg" class="img-responsive">
                <div class="carousel-caption">
                    <h3>Outside</h3>
                    <p>The atmosphere in perfect.</p>
                </div>
            </div>

            <div class="item">
                <img src="~/Content/Images/beerbw.jpg" width="1200" height="700">
                <div class="carousel-caption">
                    <h3>Nice drinks</h3>
                    <p>Come and enjoy.</p>
                </div>
            </div>

            <div class="item">
                <img src="../../Content/Images/insidebw.jpg" alt="Los Angeles" width="1200" height="700">
                <div class="carousel-caption">
                    <h3>Interior</h3>
                    <p>Most comfortable design!</p>
                </div>
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    @Html.Partial("_NavBar")

    @if (!(Request.IsAuthenticated && User.IsInRole("Admin")))
    {
        @Html.Partial("_Carousel")
    }

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Ivan's Pub</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

Views/Shared/_NavBar.cshtml
@using IvanCafe.Models
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Ivan's Pub", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Drink", "Index", "Product", new { productTypeID = 1 }, null)</li>
                <li>@Html.ActionLink("Snack", "Index", "Product", new { productTypeID = 2 }, null)</li>
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <li>
                        @Html.ActionLink("Customer Orders", "Index", "OrderDetail")
                    </li>
                }


                @if (!(Request.IsAuthenticated && User.IsInRole("Admin")))
                {
                    <li>
                        @{ Html.RenderAction("CartSummary", "Cart"); }
                    </li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

Views/Shared/_TabMenu.cshtml
<!-- Container (TabMenu Section) -->
<div id="menu" class="container">
    <ul class="nav nav-tabs">
        <li class="active">@Html.ActionLink("Order Now", "Index", "Product")</li>
        <li>@Html.ActionLink("Drink", "Index", "Product", new { productTypeID = 1 }, null)</li>
        <li>@Html.ActionLink("Snack", "Index", "Product", new { productTypeID = 2 }, null)</li>

    </ul>
   
</div>