Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IvanCafe.Models
{
    public class Cart
    {
        PubDbContext db = new PubDbContext();

        string OrderCartId { get; set; }

        public const string CartSessionKey = "SessionId";

        public static Cart GetCart(HttpContextBase context)
        {
            var cart = new Cart();
            cart.OrderCartId = cart.GetCartId(context);
            return cart;
        }

        // Helper method to simplify shopping cart calls
        public static Cart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }

        public void AddToCart(Product product)
        {
            // Get the matching cart and album instances
            var cartItem = db.CartItems.SingleOrDefault(c => c.SessionId == OrderCartId && c.ProductId == product.Id);

            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new CartItem
                {
                    ProductId = product.Id,
                    SessionId = OrderCartId,
                    Count = 1,
                    DateCreated = DateTime.Now
                };

                db.CartItems.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, then add one to the quantity
                cartItem.Count++;
            }

            // Save changes
            db.SaveChanges();
        }

        public int RemoveFromCart(int id)
        {
            // Get the cart
            var cartItem = db.CartItems.Single(cart => cart.SessionId == OrderCartId && cart.CartItemId == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    db.CartItems.Remove(cartItem);
                }

                // Save changes
                db.SaveChanges();
            }

            return itemCount;
        }

        public void EmptyCart()
        {
            var cartItems = db.CartItems.Where(cart => cart.SessionId == OrderCartId);

            foreach (var cartItem in cartItems)
            {
                db.CartItems.Remove(cartItem);
            }

            // Save changes
            db.SaveChanges();
        }

        public List<CartItem> GetCartItems()
        {
            return db.CartItems.Where(cart => cart.SessionId == OrderCartId).ToList();
        }

        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in db.CartItems
                          where cartItems.SessionId == OrderCartId
                          select (int?)cartItems.Count).Sum();

            // Return 0 if all entries are null
            return count ?? 0;
        }

        public decimal GetTotal()
        {
            // Multiply album price by count of that album to get 
            // the current price for each of those albums in the cart
            // sum all album price totals to get the cart total
            decimal? total = (from cartItems in db.CartItems
                              where cartItems.SessionId == OrderCartId
                              select (int?)cartItems.Count * cartItems.Product.Price).Sum();
            return total ?? decimal.Zero;
        }

        public int CreateOrder(Order order)
        {
            decimal orderTotal = 0;

            var cartItems = GetCartItems();

            // Iterate over the items in the cart, adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    ProductId = item.ProductId,
                    OrderId = order.Id,
                    UnitPrice = item.Product.Price,
                    Quantity = item.Count
                };

                // Set the order total of the shopping cart
                orderTotal += (item.Count * item.Product.Price);

                db.OrderDetails.Add(orderDetail);

            }

            // Set the order's total to the orderTotal count
            order.Total = orderTotal;

            // Save the order
            db.SaveChanges();

            // Empty the shopping cart
            EmptyCart();

            // Return the OrderId as the confirmation number
            return order.Id;
        }

        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] = context.User.Identity.Name;
                }
                else
                {
                    // Generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();

                    // Send tempCartId back to client as a cookie
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }

            return context.Session[CartSessionKey].ToString();
        }

        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = db.CartItems.Where(c => c.SessionId == OrderCartId);

            foreach (CartItem item in shoppingCart)
            {
                item.SessionId = userName;
            }
            db.SaveChanges();
        }
    }
}

Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using IvanCafe.Models;
using IvanCafe.ViewModels;

namespace IvanCafe.Controllers
{
    public class CartController : Controller
    {
        PubDbContext db = new PubDbContext();
        
        // GET: /Cart/
        public ActionResult Index()
        {
            var cart = Cart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new OrderViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the product from the database
            var addedProduct = db.Products
                .Single(product => product.Id == id);

            // Add it to the shopping cart
            var cart = Cart.GetCart(this.HttpContext);

            cart.AddToCart(addedProduct);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /Cart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = Cart.GetCart(this.HttpContext);

            // Get the name of the product to display confirmation
            string productName = db.CartItems
                .Single(item => item.CartItemId == id).Product.Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new RemoveFromOrderViewModel
            {
                Message = Server.HtmlEncode(productName) +
                    " has been removed from your order.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /Cart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = Cart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("_CartCount");
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using IvanCafe.Models;

namespace IvanCafe.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        PubDbContext db = new PubDbContext();

        // GET: /Order/Confirm
        public ActionResult Confirm()
        {
            return View();
        }

        //
        // POST: /Order/ConfirmOrder
        [HttpPost]
        public ActionResult Confirm(FormCollection values)
        {
            var order = new Order();
            UpdateModel(order);

            order.Username = User.Identity.Name;
            order.OrderDate = DateTime.Now;

            //Save Order
            db.Orders.Add(order);
            db.SaveChanges();

            //Process the order
            var cart = Cart.GetCart(this.HttpContext);
            cart.CreateOrder(order);

            return RedirectToAction("Complete", new { id = order.Id });

        }

        //
        // GET: /Order/Complete
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            bool isValid = db.Orders.Any(
                o => o.Id == id &&
                     o.Username == User.Identity.Name);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

Views/Cart/Index.cshtml
@model IvanCafe.ViewModels.OrderViewModel

@{
    ViewBag.Title = "Index";
}

<script src="/Scripts/jquery-3.4.1.min.js"
        type="text/javascript"></script>
<script type="text/javascript">
$(function () {
        // Document.ready -> link up remove event handler
           $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/Cart/RemoveFromCart", {"id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Cart (' + data.CartCount + ')');
                    });
            }
        });
    });</script>
<h3>
    <em>Place</em> your order:
</h3>
<p class="button">
    @Html.ActionLink("Place Order>> ", "Confirm", "Order", "", new { @class = "btn btn-primary btn-success" })
</p>
<div id="update-message">
</div>
<div class="container">
    <table class="table">
        <tr>
            <th>
                Album Name
            </th>
            <th>
                Price (each)
            </th>
            <th>
                Quantity
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.CartItems)
        {
            <tr id="row-@item.CartItemId" class=".table-hover">
                <td>
                    @Html.ActionLink(item.Product.Name,
                        "Details", "Product", new { id = item.ProductId }, null)
                </td>
                <td>
                    @item.Product.Price
                </td>
                <td id="item-count-@item.CartItemId">
                    @item.Count
                </td>
                <td>
                    <a href="#" class="RemoveLink"
                       data-id="@item.CartItemId">
                        Remove from cart
                    </a>

                </td>
            </tr>
        }
        <tr>
            <td>
                Total
            </td>
            <td>
            </td>
            <td>
            </td>
            <td id="cart-total">
                @Model.CartTotal
            </td>
        </tr>
    </table>
</div>

Views/Cart/_CartCount.cshtml
@Html.ActionLink("Review ordered item (" + ViewData["CartCount"] + ")",
    "Index",
    "",
    new { id = "cart-status" })